[tool.poetry]
name = "yukkit-e2b-mcp-server"
version = "0.2.1"
description = "E2B MCP Server"
authors = ["yukkit <yukkit@126.copm>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/yukkit/e2b-mcp-server"
repository = "https://github.com/yukkit/e2b-mcp-server/tree/main/packages/python"
packages = [{ include = "e2b_mcp_server" }]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"

e2b-code-interpreter = "^1.0.2"
mcp = "^1.23.3"
pydantic = "^2.10.2"
python-dotenv = "1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/yukkit/e2b-mcp-server/issues"
